<!DOCTYPE html>

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<html lang="en">

<body>
    <h1>${message}</h1>

    <spring:url value="/test.txt" htmlEscape="true" var="springUrl" />
    <c:url value="/test.txt" var="url"/>
	
	<ul>
	   <li><a href="${springUrl}">URL generated by Spring</a></li>
	   <li><a href="${url}">URL generated by JSTL</a></li>
	</ul> 
    
    
</body>

</html>